nightwatch-chrome-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        cd nightwatch-chrome-tryout
          yarn
          yarn test
          yarn helloworld
        cd ..
