chrome-selenium-hub-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - run: |
        cd $GITHUB_WORKSPACE/_ref/docker-selenium
          docker-compose -f docker-compose-v3.yml up -d
        cd $GITHUB_WORKSPACE


    - run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv

        export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        export PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        pipenv --help

        cd $GITHUB_WORKSPACE/chrome-selenium-hub-tryout
          pipenv sync
          pipenv run python3 ./main.py
        cd $GITHUB_WORKSPACE

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
