selenium-viewport-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - run: |
        pushd $GITHUB_WORKSPACE/selenium-viewport-tryout
          ./scripts/up_docker_selenium.sh &

          echo 'sleep a while to let docker steady'
          sleep 30
        popd

    - run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv

        export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        export PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        pipenv --help

        pushd $GITHUB_WORKSPACE/selenium-viewport-tryout
          pipenv sync
          pipenv run python3 ./main.py
        popd

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: 'upload-artifact-tryout'
        path: selenium-viewport-tryout/screenshot/*.png
