name: master_build
on:
  push:

jobs:

  # 
  # /home/logic/_workspace/selenium-playlist/chrome-selenium-hub-tryout/build.yml
  # 
  chrome-selenium-hub-tryout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
  
      - run: |
          cd $GITHUB_WORKSPACE/_ref/docker-selenium
            docker-compose -f docker-compose-v3.yml up -d
            sleep 30
          cd $GITHUB_WORKSPACE
  
      - run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
  
          cd $GITHUB_WORKSPACE/chrome-selenium-hub-tryout
            pipenv sync
            pipenv run python3 ./main.py
          cd $GITHUB_WORKSPACE
  
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
      - uses: actions/upload-artifact@v2
        with:
          name: 'chrome-selenium-hub-tryout'
          path: chrome-selenium-hub-tryout/screenshot/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/docker-selenium-hub-tryout/build.yml
  # 
  docker-selenium-hub-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
  
      - run: |
          cd $GITHUB_WORKSPACE/_ref/docker-selenium
            docker-compose -f docker-compose-v3.yml up -d
          cd $GITHUB_WORKSPACE
  
  # 
  # /home/logic/_workspace/selenium-playlist/firefox-selenium-hub-tryout/build.yml
  # 
  firefox-selenium-hub-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
  
      - run: |
          cd $GITHUB_WORKSPACE/_ref/docker-selenium
            docker-compose -f docker-compose-v3.yml up -d
          cd $GITHUB_WORKSPACE
  
      - run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
  
          cd $GITHUB_WORKSPACE/firefox-selenium-hub-tryout
            pipenv sync
            pipenv run python3 ./main.py
          cd $GITHUB_WORKSPACE
  
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
      - uses: actions/upload-artifact@v2
        with:
          name: 'firefox-selenium-hub-tryout'
          path: firefox-selenium-hub-tryout/screenshot/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-chrome-tryout/build.yml
  # 
  nightwatch-chrome-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-chrome-tryout
            yarn
            yarn test
            yarn helloworld
          cd ..
  
      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: nightwatch-chrome-tryout/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-html-reporter-tryout/build.yml
  # 
  nightwatch-html-reporter-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-html-reporter-tryout
            yarn
            yarn test
            yarn helloworld
          cd ..
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-pageobject-tryout/build.yml
  # 
  nightwatch-pageobject-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-pageobject-tryout
            yarn
            yarn test
            yarn helloworld
          cd ..
  
      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: nightwatch-pageobject-tryout/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-parallel-run-tryout/build.yml
  # 
  nightwatch-parallel-run-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-parallel-run-tryout
            yarn
            yarn test
            yarn helloworld
          cd ..
  
      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: nightwatch-parallel-run-tryout/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-tags-tryout/build.yml
  # 
  nightwatch-tags-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-tags-tryout
            yarn
            yarn test
            yarn dev
          cd ..
  
  # 
  # /home/logic/_workspace/selenium-playlist/nightwatch-tryout/build.yml
  # 
  nightwatch-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd nightwatch-tryout
            yarn
            yarn test
            yarn helloworld-ecosia
            yarn helloworld-example
          cd ..
  
      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: nightwatch-tryout/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/selenium-page-object-tryout/build.yml
  # 
  selenium-page-object-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
  
      - run: |
          pushd $GITHUB_WORKSPACE/selenium-page-object-tryout
            ./scripts/up_docker_selenium.sh &
  
            echo 'sleep a while to let docker steady'
            sleep 30
          popd
  
      - run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
  
          pushd $GITHUB_WORKSPACE/selenium-page-object-tryout
            pipenv sync
            pipenv run python3 ./main.py
          popd
  
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
      - uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: selenium-page-object-tryout/screenshot/*.png
  
  # 
  # /home/logic/_workspace/selenium-playlist/selenium-viewport-tryout-old/build.yml
  # 
  selenium-viewport-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
  
      - run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
  
          cd $GITHUB_WORKSPACE/selenium-viewport-tryout
            pipenv sync
            pipenv run python3 ./main.py
          cd $GITHUB_WORKSPACE
  
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
      - uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: selenium-viewport-tryout/screenshot/*.png
  
  

  # 
  # /home/logic/_workspace/selenium-playlist/github-build-merger/subjob.yml
  # 
  test_merger:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: run test
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
          github-build-merger/test.sh
  
  merge:
    needs: [chrome-selenium-hub-tryout, docker-selenium-hub-tryout, firefox-selenium-hub-tryout, nightwatch-chrome-tryout, nightwatch-html-reporter-tryout, nightwatch-pageobject-tryout, nightwatch-parallel-run-tryout, nightwatch-tags-tryout, nightwatch-tryout, selenium-page-object-tryout, selenium-viewport-tryout, test_merger]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: run merge
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          cd github-build-merger
            pipenv sync
  
            pipenv run python3 ./merge.py
          cd ..
  
  
